[project]
name = 'stablelend'
description = 'First native USDCx lending protocol on Stacks. The Global Yield Layer for Bitcoin.'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

# Production contract
[contracts.stablelend-pool-v2]
path = 'contracts/stablelend-pool-v2.clar'
clarity_version = 2
epoch = 'latest'

[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
