[project]
name = 'stablelend'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.lending-pool]
path = 'contracts/lending-pool.clar'
clarity_version = 2
epoch = 'latest'

[contracts.sip-010-trait]
path = 'contracts/sip-010-trait.clar'
clarity_version = 2
epoch = 'latest'

[contracts.mock-usdcx]
path = 'contracts/mock-usdcx.clar'
clarity_version = 2
epoch = 'latest'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
